export default [
    {
        id: 0,
        subject: "Software Engineering",
        contents: [
            { id: 0, subTopic: "Software Crisis" },
            { id: 1, subTopic: "Software Life Cycle Models" },
            { id: 2, subTopic: "Waterfall Model" },
            { id: 3, subTopic: "Prototype Model" },
            { id: 4, subTopic: "Spiral Models" },
            { id: 5, subTopic: "Agile model" },
            { id: 6, subTopic: "Requirement engineering" },
            { id: 7, subTopic: "Requirement elicitation techniques (FAST)" },
            { id: 8, subTopic: "Requirement elicitation techniques (QFD)" },
            { id: 9, subTopic: "Requirement analysis using DFD" },
            { id: 10, subTopic: "Use-case, sequence and class diagram" },
            { id: 11, subTopic: "ER Diagrams" },
            { id: 12, subTopic: "Requirements documentation: SRS" },
            { id: 13, subTopic: "Characteristics & organization of SRS" },
            { id: 14, subTopic: "Software Metrics: Definition and Need" },
            { id: 15, subTopic: "Types of Metrics: Product Metrics" },
            { id: 16, subTopic: "Types of Metrics: Process Metrics" },
            { id: 17, subTopic: "Types of Metrics: Project Metrics" },
            { id: 18, subTopic: "Size Estimation: lines of Code" },
            { id: 19, subTopic: "Size Estimation: Function Count" },
            { id: 20, subTopic: "Halstead Software Science measure" },
            { id: 21, subTopic: "Cost Estimation: Need" },
            { id: 22, subTopic: "Cost Estimation: Models COCOMO (Basic model)" },
            { id: 23, subTopic: "Cost Estimation: Models COCOMO (Intermediate model)" },
            { id: 24, subTopic: "Risk Management: Software Risks" },
            { id: 25, subTopic: "Risk Management: Types of risk" },
            { id: 26, subTopic: "Risk Management: Risk management activities" },
            { id: 27, subTopic: "Cohesion" },
            { id: 28, subTopic: "Coupling" },
            { id: 29, subTopic: "Classification of Cohesiveness" },
            { id: 30, subTopic: "Classification of Coupling" },
            { id: 31, subTopic: "Quality management: Quality concept" },
            { id: 32, subTopic: "Quality management: Software quality assurance" },
            { id: 33, subTopic: "Quality management: Total Quality Management (TQM)" },
            { id: 34, subTopic: "Software review" },
            { id: 35, subTopic: "Software inspection" },
            { id: 36, subTopic: "Software Implementation: Structured coding techniques" },
            { id: 37, subTopic: "Software Implementation: Coding style" },
            { id: 38, subTopic: "Software Implementation: Standards and guidelines" },
            { id: 39, subTopic: "Software Implementation: Documentation guidelines" },
            { id: 40, subTopic: "Reverse Engineering" },
            { id: 41, subTopic: "Software Re-engineering" },
            { id: 42, subTopic: "Configuration Management" },
            { id: 43, subTopic: "Testing Process" },
            { id: 44, subTopic: "Levels of Testing: Unit testing" },
            { id: 45, subTopic: "Levels of Testing: Integration testing" },
            { id: 46, subTopic: "Levels of Testing: System testing" },
            { id: 47, subTopic: "Types of Testing: Manual testing" },
            { id: 48, subTopic: "Types of Testing: Automation Testing" },
            { id: 49, subTopic: "Methods of Testing: Black box Testing" },
            { id: 50, subTopic: "Methods of Testing: White box Testing" },
            { id: 51, subTopic: "Methods of Testing: Grey Box Testing" },
            { id: 52, subTopic: "Validation" },
            { id: 53, subTopic: "Verification" },
            { id: 54, subTopic: "Alpha-Beta testing" },
            { id: 55, subTopic: "Acceptance testing" },
            { id: 56, subTopic: "Functional Testing" },
            { id: 57, subTopic: "Functional Testing: Types" },
            { id: 58, subTopic: "Structural Testing" },
            { id: 59, subTopic: "Difference between: Testing" },
            { id: 60, subTopic: "Difference between: Debugging" },
            { id: 61, subTopic: "Management of Maintenance" },
            { id: 62, subTopic: "The Maintenance Process" },
            { id: 63, subTopic: "Types of maintenance: Preventive Maintenance" },
            { id: 64, subTopic: "Types of maintenance: Perceptive Maintenance" },
            { id: 65, subTopic: "Types of maintenance: Adaptive Maintenance" },
            { id: 66, subTopic: "Types of maintenance: Corrective Maintenance" },
            { id: 67, subTopic: "Maintenance tools" },
            { id: 68, subTopic: "Maintenance techniques" }
        ]
    },
    {
        id: 1,
        subject: "Operating Systems",
        contents: [
            { id: 0, subTopic: "What is an Operating System" },
            { id: 1, subTopic: "Functions of Operating System" },
            { id: 2, subTopic: "Simple Batch Systems" },
            { id: 3, subTopic: "Multi-programmed Batch systems" },
            { id: 4, subTopic: "Time-Sharing Systems" },
            { id: 5, subTopic: "Personal-computer systems" },
            { id: 6, subTopic: "Parallel systems" },
            { id: 7, subTopic: "Distributed Systems" },
            { id: 8, subTopic: "Real-Time Systems" },
            { id: 9, subTopic: "Introduction to Linux" },
            { id: 10, subTopic: "Architecture of Linux OS" },
            { id: 11, subTopic: "Basic directory structure of Linux" },
            { id: 12, subTopic: "Basic commands of Linux" },
            { id: 13, subTopic: "Vi Editor basics" },
            { id: 14, subTopic: "Modes of vi Editor" },
            { id: 15, subTopic: "Writing, saving, and executing a shell script in vi editor" },
            { id: 16, subTopic: "Processes: Process Concept" },
            { id: 17, subTopic: "Process Scheduling" },
            { id: 18, subTopic: "Operation on Processes" },
            { id: 19, subTopic: "CPU Scheduling Concepts" },
            { id: 20, subTopic: "Scheduling Criteria" },
            { id: 21, subTopic: "Scheduling Algorithms" },
            { id: 22, subTopic: "Process Synchronization Background" },
            { id: 23, subTopic: "The Critical-Section Problem" },
            { id: 24, subTopic: "Semaphores solution to critical section problem" },
            { id: 25, subTopic: "Process-related commands in Linux" },
            { id: 26, subTopic: "Memory Management Background" },
            { id: 27, subTopic: "Logical versus Physical Address space" },
            { id: 28, subTopic: "Swapping" },
            { id: 29, subTopic: "Contiguous allocation" },
            { id: 30, subTopic: "Segmentation" },
            { id: 31, subTopic: "Paging" },
            { id: 32, subTopic: "Demand Paging" },
            { id: 33, subTopic: "Performance of Demand Paging" },
            { id: 34, subTopic: "Page Replacement" },
            { id: 35, subTopic: "Page-replacement Algorithms" },
            { id: 36, subTopic: "Allocation of Frames" },
            { id: 37, subTopic: "Thrashing" },
            { id: 38, subTopic: "Deadlocks System Model" },
            { id: 39, subTopic: "Deadlock Characterization" },
            { id: 40, subTopic: "Methods for Handling Deadlocks" },
            { id: 41, subTopic: "Deadlock Prevention" },
            { id: 42, subTopic: "Deadlock Avoidance" },
            { id: 43, subTopic: "Deadlock Detection" },
            { id: 44, subTopic: "Recovery from Deadlock" },
            { id: 45, subTopic: "File Concept" },
            { id: 46, subTopic: "Access methods" },
            { id: 47, subTopic: "Directory and Disk structure" },
            { id: 48, subTopic: "File Protection" },
            { id: 49, subTopic: "Linux File Security" },
            { id: 50, subTopic: "Permission types" },
            { id: 51, subTopic: "Examining permissions" },
            { id: 52, subTopic: "Changing permissions (symbolic method)" },
            { id: 53, subTopic: "Changing permissions (numeric method)" }
        ]
    },
    {
        id: 2,
        subject: "Database Management System",
        contents: [
            { id: 0, subTopic: "An overview of database management system" },
            { id: 1, subTopic: "Characteristics of database approach" },
            { id: 2, subTopic: "DBMS architecture" },
            { id: 3, subTopic: "Client/server" },
            { id: 4, subTopic: "Data Models" },
            { id: 5, subTopic: "Introduction to Distributed Data processing" },
            { id: 6, subTopic: "Schema and instances" },
            { id: 7, subTopic: "Data independence" },
            { id: 8, subTopic: "Data Modelling using Entity Relationship Model" },
            { id: 9, subTopic: "Entity, Entity types, and entity set" },
            { id: 10, subTopic: "Notation for ER diagram" },
            { id: 11, subTopic: "Attributes and keys" },
            { id: 12, subTopic: "Types of attributes and keys" },
            { id: 13, subTopic: "Relationships" },
            { id: 14, subTopic: "Relation types" },
            { id: 15, subTopic: "Weak entities" },
            { id: 16, subTopic: "Enhanced E-R" },
            { id: 17, subTopic: "Specialization and generalization" },
            { id: 18, subTopic: "Introduction to SQL" },
            { id: 19, subTopic: "Overview and Characteristics of SQL" },
            { id: 20, subTopic: "Advantage of SQL" },
            { id: 21, subTopic: "SQL data types and literals" },
            { id: 22, subTopic: "Types of SQL commands" },
            { id: 23, subTopic: "Logical operators" },
            { id: 24, subTopic: "Null Values" },
            { id: 25, subTopic: "Integrity constraints" },
            { id: 26, subTopic: "Introduction to Nested Queries" },
            { id: 27, subTopic: "Correlated Nested Queries" },
            { id: 28, subTopic: "Set-Comparison Operators" },
            { id: 29, subTopic: "Aggregate Operators" },
            { id: 30, subTopic: "Joins" },
            { id: 31, subTopic: "Overview of other SQL Objects" },
            { id: 32, subTopic: "Relational Data Models" },
            { id: 33, subTopic: "Relational algebra" },
            { id: 34, subTopic: "Set Theoretic operations" },
            { id: 35, subTopic: "Relational calculus" },
            { id: 36, subTopic: "Join operations" },
            { id: 37, subTopic: "ER to relational mapping" },
            { id: 38, subTopic: "Data Normalization" },
            { id: 39, subTopic: "Transaction Processing" },
            { id: 40, subTopic: "Database recovery and Database Security" },
            { id: 41, subTopic: "Overview of Query by Language" },
            { id: 42, subTopic: "NoSql databases" }
        ]
    },
    {
        id: 3,
        subject: "Computer Networks",
        contents: [
            { id: 0, subTopic: "Basic Concepts: Components of data communication" },
            { id: 1, subTopic: "Basic Concepts: Distributed processing" },
            { id: 2, subTopic: "Basic Concepts: Line configuration" },
            { id: 3, subTopic: "Basic Concepts: Topology" },
            { id: 4, subTopic: "Basic Concepts: Transmission mode" },
            { id: 5, subTopic: "Basic Concepts: Categories of networks" },
            { id: 6, subTopic: "OSI and TCP/IP Models: Layers and their functions" },
            { id: 7, subTopic: "OSI and TCP/IP Models: Comparison of models" },
            { id: 8, subTopic: "Transmission Media: Guided and unguided" },
            { id: 9, subTopic: "Transmission Media: Attenuation" },
            { id: 10, subTopic: "Transmission Media: Distortion" },
            { id: 11, subTopic: "Transmission Media: Noise" },
            { id: 12, subTopic: "Transmission Media: Throughput" },
            { id: 13, subTopic: "Transmission Media: Propagation speed and time" },
            { id: 14, subTopic: "Transmission Media: Wavelength" },
            { id: 15, subTopic: "Transmission Media: Shannon Capacity" },
            { id: 16, subTopic: "Telephony: Multiplexing" },
            { id: 17, subTopic: "Telephony: WDM" },
            { id: 18, subTopic: "Telephony: TDM" },
            { id: 19, subTopic: "Telephony: FDM" },
            { id: 20, subTopic: "Telephony: Circuit switching" },
            { id: 21, subTopic: "Telephony: Packet switching" },
            { id: 22, subTopic: "Telephony: Message switching" },
            { id: 23, subTopic: "Data Link Layer: Types of errors" },
            { id: 24, subTopic: "Data Link Layer: Framing (character and bit stuffing)" },
            { id: 25, subTopic: "Data Link Layer: Error detection & correction methods" },
            { id: 26, subTopic: "Data Link Layer: Flow control" },
            { id: 27, subTopic: "Data Link Layer: Protocols: Stop & wait ARQ" },
            { id: 28, subTopic: "Data Link Layer: Protocols: Go-Back-N ARQ" },
            { id: 29, subTopic: "Data Link Layer: Protocols: Selective repeat ARQ" },
            { id: 30, subTopic: "Network Layer: Internetworking & Devices" },
            { id: 31, subTopic: "Network Layer: Addressing: IPv4 and IPv6 addressing" },
            { id: 32, subTopic: "Network Layer: Addressing: IPv4 subnetting" },
            { id: 33, subTopic: "Network Layer: Routing: Unicast Routing Protocols: RIP, OSPF, BGP" },
            { id: 34, subTopic: "Network Layer: Routing: Routing Methods- Static and Dynamic Routing" },
            { id: 35, subTopic: "Network Layer: Routing basic commands" },
            { id: 36, subTopic: "Network Layer: Routing: Distance vector protocol" },
            { id: 37, subTopic: "Network Layer: Routing: Link state protocol" },
            { id: 38, subTopic: "Transport and upper layers in OSI Model: Transport layer functions and Protocols" },
            { id: 39, subTopic: "Transport and upper layers in OSI Model: Connection management" },
            { id: 40, subTopic: "Transport and upper layers in OSI Model: Functions of session layers" },
            { id: 41, subTopic: "Transport and upper layers in OSI Model: Presentation layer" },
            { id: 42, subTopic: "Transport and upper layers in OSI Model: Application layer" }
        ]
    }
];
